//! Deterministic Caddy route rendering.
//!
//! The registry is the single source of truth. Rendering is a pure function of
//! the sorted app list and a small config, so the same registry always yields
//! byte-identical output. Every managed route follows one shape:
//!
//! 1. strip any browser-supplied `X-RepoBox-*` identity header;
//! 2. ask the control plane (`forward_auth`) whether this request may proceed;
//! 3. copy only the gate-issued identity headers onto the request;
//! 4. serve: `file_server` for static apps, `reverse_proxy` to a loopback
//!    origin for proxy apps.
//!
//! Visibility and enabled/disabled state are *not* baked into the route: the
//! gate evaluates them per request, so toggling them in the UI takes effect
//! immediately without re-rendering.

use crate::model::{App, AppKind, validate_app_name, validate_target};

#[derive(Debug, Clone)]
pub struct RenderConfig {
    /// Public apex domain apps hang off (`repo.box` -> `<name>.repo.box`).
    pub domain: String,
    /// Loopback address of the control plane gate.
    pub gate: String,
    /// Directory every static root must live under.
    pub apps_root: String,
}

/// Identity headers the gate may issue. The generated `copy_headers` list and
/// the gate implementation must agree, so both read this constant.
pub const IDENTITY_HEADERS: &[&str] = &[
    "X-RepoBox-User",
    "X-RepoBox-User-Id",
    "X-RepoBox-Role",
    "X-RepoBox-Auth",
    "X-RepoBox-App",
];

/// Header that marks a request as coming from Caddy's forward_auth hop.
pub const GATE_MARKER_HEADER: &str = "X-RepoBox-Gate";
pub const GATE_APP_HEADER: &str = "X-RepoBox-Gate-App";

pub fn validate_for_render(app: &App, cfg: &RenderConfig) -> Result<(), String> {
    validate_app_name(&app.name).map_err(|e| format!("app '{}': {e}", app.name))?;
    let target =
        validate_target(app.kind, &app.target).map_err(|e| format!("app '{}': {e}", app.name))?;
    if app.kind == AppKind::Static {
        let root = cfg.apps_root.trim_end_matches('/');
        if root.is_empty() || !target.starts_with(&format!("{root}/")) {
            return Err(format!(
                "app '{}': static root {} must be under {}",
                app.name, target, cfg.apps_root
            ));
        }
    }
    if !cfg.gate.starts_with("127.0.0.1:") && !cfg.gate.starts_with("[::1]:") {
        return Err(format!("gate address {} must be loopback", cfg.gate));
    }
    Ok(())
}

pub fn render(apps: &[App], cfg: &RenderConfig) -> Result<String, String> {
    let mut sorted: Vec<&App> = apps.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    let mut seen = std::collections::HashSet::new();
    for app in &sorted {
        validate_for_render(app, cfg)?;
        if !seen.insert(app.name.as_str()) {
            return Err(format!("duplicate app name '{}'", app.name));
        }
    }

    let mut out = String::new();
    out.push_str("# GENERATED by `repobox-platform routes render`. Do not edit by hand.\n");
    out.push_str("# Every managed app: strip browser identity headers -> ask the control\n");
    out.push_str("# plane gate -> copy gate-issued identity -> serve. Visibility and\n");
    out.push_str("# enabled state are evaluated by the gate per request.\n");
    out.push_str(&format!("# gate: {}\n", cfg.gate));
    out.push_str(&format!("# managed apps: {}\n", sorted.len()));

    for app in sorted {
        let target = validate_target(app.kind, &app.target)?;
        out.push('\n');
        out.push_str(&format!(
            "# app: {} ({} -> {})\n",
            app.name,
            app.kind.as_str(),
            target
        ));
        out.push_str(&format!("{} {{\n", app.host(&cfg.domain)));
        out.push_str("\theader {\n");
        out.push_str("\t\tX-Content-Type-Options \"nosniff\"\n");
        out.push_str("\t\tReferrer-Policy \"strict-origin-when-cross-origin\"\n");
        out.push_str(
            "\t\tStrict-Transport-Security \"max-age=31536000; includeSubDomains; preload\"\n",
        );
        out.push_str("\t\t-Server\n");
        out.push_str("\t}\n");
        out.push_str("\troute {\n");
        out.push_str("\t\trequest_header -X-RepoBox-*\n");
        out.push_str(&format!("\t\tforward_auth {} {{\n", cfg.gate));
        out.push_str("\t\t\turi /gate/verify\n");
        out.push_str(&format!(
            "\t\t\tcopy_headers {}\n",
            IDENTITY_HEADERS.join(" ")
        ));
        out.push_str(&format!("\t\t\theader_up {GATE_MARKER_HEADER} 1\n"));
        out.push_str(&format!("\t\t\theader_up {GATE_APP_HEADER} {}\n", app.name));
        out.push_str("\t\t}\n");
        match app.kind {
            AppKind::Static => {
                out.push_str(&format!("\t\troot * {target}\n"));
                out.push_str("\t\tfile_server\n");
            }
            AppKind::Proxy => {
                out.push_str(&format!("\t\treverse_proxy {target}\n"));
            }
        }
        out.push_str("\t}\n");
        out.push_str("}\n");
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::Visibility;

    fn app(name: &str, kind: AppKind, target: &str) -> App {
        App {
            id: 0,
            name: name.into(),
            title: name.into(),
            description: String::new(),
            owner_id: 1,
            kind,
            target: target.into(),
            visibility: Visibility::Private,
            enabled: true,
            created_at: 0,
            updated_at: 0,
        }
    }

    fn cfg() -> RenderConfig {
        RenderConfig {
            domain: "repo.box".into(),
            gate: "127.0.0.1:3230".into(),
            apps_root: "/srv/repobox-platform/apps".into(),
        }
    }

    #[test]
    fn deterministic_and_sorted() {
        let a = app("zeta", AppKind::Proxy, "127.0.0.1:3231");
        let b = app("alpha", AppKind::Static, "/srv/repobox-platform/apps/alpha");
        let one = render(&[a.clone(), b.clone()], &cfg()).unwrap();
        let two = render(&[b, a], &cfg()).unwrap();
        assert_eq!(one, two);
        let ia = one.find("alpha.repo.box {").unwrap();
        let iz = one.find("zeta.repo.box {").unwrap();
        assert!(ia < iz);
    }

    #[test]
    fn shape_of_generated_route() {
        let out = render(
            &[app("demo-private", AppKind::Proxy, "localhost:3231")],
            &cfg(),
        )
        .unwrap();
        assert!(out.contains("demo-private.repo.box {"));
        assert!(out.contains("request_header -X-RepoBox-*"));
        assert!(out.contains("forward_auth 127.0.0.1:3230 {"));
        assert!(out.contains("uri /gate/verify"));
        assert!(out.contains("copy_headers X-RepoBox-User X-RepoBox-User-Id X-RepoBox-Role X-RepoBox-Auth X-RepoBox-App"));
        assert!(out.contains("header_up X-RepoBox-Gate-App demo-private"));
        assert!(
            out.contains("reverse_proxy 127.0.0.1:3231"),
            "localhost normalised"
        );
        let strip = out.find("request_header -X-RepoBox-*").unwrap();
        let fa = out.find("forward_auth").unwrap();
        let rp = out.find("reverse_proxy").unwrap();
        assert!(strip < fa && fa < rp, "strip, then gate, then serve");
        let s = render(
            &[app("s", AppKind::Static, "/srv/repobox-platform/apps/s")],
            &cfg(),
        )
        .unwrap();
        assert!(s.contains("root * /srv/repobox-platform/apps/s\n\t\tfile_server"));
    }

    #[test]
    fn rejects_unsafe_input() {
        assert!(render(&[app("bad name", AppKind::Proxy, "127.0.0.1:1")], &cfg()).is_err());
        assert!(render(&[app("auth", AppKind::Proxy, "127.0.0.1:1")], &cfg()).is_err());
        assert!(render(&[app("x", AppKind::Proxy, "0.0.0.0:1")], &cfg()).is_err());
        assert!(
            render(&[app("x", AppKind::Static, "/etc")], &cfg()).is_err(),
            "outside apps root"
        );
        assert!(
            render(
                &[app("x", AppKind::Static, "/srv/repobox-platform/apps/../x")],
                &cfg()
            )
            .is_err()
        );
        let dup = [
            app("x", AppKind::Proxy, "127.0.0.1:1"),
            app("x", AppKind::Proxy, "127.0.0.1:2"),
        ];
        assert!(render(&dup, &cfg()).is_err());
        let mut c = cfg();
        c.gate = "0.0.0.0:3230".into();
        assert!(render(&[app("x", AppKind::Proxy, "127.0.0.1:1")], &c).is_err());
    }
}
