//! Deterministic Caddy route rendering.
//!
//! The registry is the single source of truth. Rendering is a pure function of
//! the sorted app list and a small config, so the same registry always yields
//! byte-identical output. Every managed route follows one shape:
//!
//! 1. strip any browser-supplied `X-RepoBox-*` identity header;
//! 2. ask the control plane (`forward_auth`) whether this request may proceed;
//! 3. copy only the gate-issued identity headers onto the request;
//! 4. serve: `file_server` for static apps, `reverse_proxy` to a loopback
//!    origin for proxy apps.
//!
//! Visibility and enabled/disabled state are *not* baked into the route: the
//! gate evaluates them per request, so toggling them in the UI takes effect
//! immediately without re-rendering.

use crate::model::{
    App, AppKind, IdentityContract, Visibility, validate_app_name, validate_target,
};

#[derive(Debug, Clone)]
pub struct RenderConfig {
    /// Public apex domain apps hang off (`repo.box` -> `<name>.repo.box`).
    pub domain: String,
    /// Loopback address of the control plane gate.
    pub gate: String,
    /// Directories a static root may live under (any one of them).
    pub apps_roots: Vec<String>,
}

/// Identity headers the gate may issue. The generated `copy_headers` list and
/// the gate implementation must agree, so both read this constant.
pub const IDENTITY_HEADERS: &[&str] = &[
    "X-RepoBox-User",
    "X-RepoBox-User-Id",
    "X-RepoBox-Role",
    "X-RepoBox-Auth",
    "X-RepoBox-App",
];

/// Header that marks a request as coming from Caddy's forward_auth hop.
pub const GATE_MARKER_HEADER: &str = "X-RepoBox-Gate";
pub const GATE_APP_HEADER: &str = "X-RepoBox-Gate-App";

pub fn validate_for_render(app: &App, cfg: &RenderConfig) -> Result<(), String> {
    validate_app_name(&app.name).map_err(|e| format!("app '{}': {e}", app.name))?;
    let target =
        validate_target(app.kind, &app.target).map_err(|e| format!("app '{}': {e}", app.name))?;
    if app.kind == AppKind::Static {
        let under_allowed_root = cfg.apps_roots.iter().any(|r| {
            let root = r.trim_end_matches('/');
            !root.is_empty() && target.starts_with(&format!("{root}/"))
        });
        if !under_allowed_root {
            return Err(format!(
                "app '{}': static root {} must be under one of: {}",
                app.name,
                target,
                cfg.apps_roots.join(", ")
            ));
        }
    }
    if !cfg.gate.starts_with("127.0.0.1:") && !cfg.gate.starts_with("[::1]:") {
        return Err(format!("gate address {} must be loopback", cfg.gate));
    }
    Ok(())
}

/// Apps that are private without the platform identity contract: they keep
/// serving, but the manifest and the renderer call them out.
pub fn pending_private(apps: &[App]) -> Vec<&App> {
    let mut v: Vec<&App> = apps
        .iter()
        .filter(|a| a.visibility == Visibility::Private && !a.identity.is_platform())
        .collect();
    v.sort_by(|a, b| a.name.cmp(&b.name));
    v
}

fn identity_note(app: &App) -> String {
    match (app.identity, app.visibility) {
        (IdentityContract::Platform, _) => "platform (gate-injected identity only; no app login)".into(),
        (IdentityContract::Pending, Visibility::Private) => {
            "PENDING REVIEW (private app registered before the identity policy; app-level login must be removed, then `app attest`)".into()
        }
        (IdentityContract::Pending, _) => "pending (public app; declaration required before it can become private)".into(),
    }
}

pub fn render(apps: &[App], cfg: &RenderConfig) -> Result<String, String> {
    let mut sorted: Vec<&App> = apps.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    let mut seen = std::collections::HashSet::new();
    for app in &sorted {
        validate_for_render(app, cfg)?;
        if !seen.insert(app.name.as_str()) {
            return Err(format!("duplicate app name '{}'", app.name));
        }
    }

    let mut out = String::new();
    out.push_str("# GENERATED by `repobox-platform routes render`. Do not edit by hand.\n");
    out.push_str("# Every managed app: strip browser identity headers -> ask the control\n");
    out.push_str("# plane gate -> copy gate-issued identity -> serve. Visibility and\n");
    out.push_str("# enabled state are evaluated by the gate per request.\n");
    out.push_str(&format!("# gate: {}\n", cfg.gate));
    out.push_str(&format!("# managed apps: {}\n", sorted.len()));

    for app in sorted {
        let target = validate_target(app.kind, &app.target)?;
        out.push('\n');
        out.push_str(&format!(
            "# app: {} ({} -> {})\n",
            app.name,
            app.kind.as_str(),
            target
        ));
        // The route shape is identical for every app: strip, gate, inject,
        // serve. The comment records the declared identity contract so the
        // rendered file doubles as the publish manifest operators review.
        out.push_str(&format!("# identity: {}\n", identity_note(app)));
        out.push_str(&format!("{} {{\n", app.host(&cfg.domain)));
        out.push_str("\theader {\n");
        out.push_str("\t\tX-Content-Type-Options \"nosniff\"\n");
        out.push_str("\t\tReferrer-Policy \"strict-origin-when-cross-origin\"\n");
        out.push_str(
            "\t\tStrict-Transport-Security \"max-age=31536000; includeSubDomains; preload\"\n",
        );
        out.push_str("\t\t-Server\n");
        out.push_str("\t}\n");
        out.push_str("\troute {\n");
        out.push_str("\t\trequest_header -X-RepoBox-*\n");
        out.push_str(&format!("\t\tforward_auth {} {{\n", cfg.gate));
        out.push_str("\t\t\turi /gate/verify\n");
        out.push_str(&format!(
            "\t\t\tcopy_headers {}\n",
            IDENTITY_HEADERS.join(" ")
        ));
        out.push_str(&format!("\t\t\theader_up {GATE_MARKER_HEADER} 1\n"));
        out.push_str(&format!("\t\t\theader_up {GATE_APP_HEADER} {}\n", app.name));
        out.push_str("\t\t}\n");
        match app.kind {
            AppKind::Static => {
                out.push_str(&format!("\t\troot * {target}\n"));
                out.push_str("\t\tfile_server\n");
            }
            AppKind::Proxy => {
                out.push_str(&format!("\t\treverse_proxy {target}\n"));
            }
        }
        out.push_str("\t}\n");
        out.push_str("}\n");
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn app(name: &str, kind: AppKind, target: &str) -> App {
        App {
            id: 0,
            name: name.into(),
            title: name.into(),
            description: String::new(),
            owner_id: 1,
            kind,
            target: target.into(),
            visibility: Visibility::Private,
            enabled: true,
            created_at: 0,
            updated_at: 0,
            identity: IdentityContract::Platform,
        }
    }

    fn cfg() -> RenderConfig {
        RenderConfig {
            domain: "repo.box".into(),
            gate: "127.0.0.1:3230".into(),
            apps_roots: vec!["/srv/repobox-platform/apps".into()],
        }
    }

    #[test]
    fn deterministic_and_sorted() {
        let a = app("zeta", AppKind::Proxy, "127.0.0.1:3231");
        let b = app("alpha", AppKind::Static, "/srv/repobox-platform/apps/alpha");
        let one = render(&[a.clone(), b.clone()], &cfg()).unwrap();
        let two = render(&[b, a], &cfg()).unwrap();
        assert_eq!(one, two);
        let ia = one.find("alpha.repo.box {").unwrap();
        let iz = one.find("zeta.repo.box {").unwrap();
        assert!(ia < iz);
    }

    #[test]
    fn shape_of_generated_route() {
        let out = render(
            &[app("demo-private", AppKind::Proxy, "localhost:3231")],
            &cfg(),
        )
        .unwrap();
        assert!(out.contains("demo-private.repo.box {"));
        assert!(out.contains("request_header -X-RepoBox-*"));
        assert!(out.contains("forward_auth 127.0.0.1:3230 {"));
        assert!(out.contains("uri /gate/verify"));
        assert!(out.contains("copy_headers X-RepoBox-User X-RepoBox-User-Id X-RepoBox-Role X-RepoBox-Auth X-RepoBox-App"));
        assert!(out.contains("header_up X-RepoBox-Gate-App demo-private"));
        assert!(
            out.contains("reverse_proxy 127.0.0.1:3231"),
            "localhost normalised"
        );
        let strip = out.find("request_header -X-RepoBox-*").unwrap();
        let fa = out.find("forward_auth").unwrap();
        let rp = out.find("reverse_proxy").unwrap();
        assert!(strip < fa && fa < rp, "strip, then gate, then serve");
        let s = render(
            &[app("s", AppKind::Static, "/srv/repobox-platform/apps/s")],
            &cfg(),
        )
        .unwrap();
        assert!(s.contains("root * /srv/repobox-platform/apps/s\n\t\tfile_server"));
    }

    #[test]
    fn manifest_names_the_identity_contract_and_flags_pending_private_apps() {
        let ok = app("ok", AppKind::Proxy, "127.0.0.1:1");
        let mut legacy = app("legacy", AppKind::Proxy, "127.0.0.1:2");
        legacy.identity = IdentityContract::Pending;
        let mut public = app("pub", AppKind::Proxy, "127.0.0.1:3");
        public.identity = IdentityContract::Pending;
        public.visibility = Visibility::PublicListed;
        let out = render(&[ok.clone(), legacy.clone(), public.clone()], &cfg()).unwrap();
        assert!(out.contains("# app: ok (proxy -> 127.0.0.1:1)\n# identity: platform (gate-injected identity only; no app login)\n"));
        assert!(out.contains("# app: legacy (proxy -> 127.0.0.1:2)\n# identity: PENDING REVIEW"));
        assert!(out.contains("# app: pub (proxy -> 127.0.0.1:3)\n# identity: pending (public app"));
        // The route itself is the same either way: strip, gate, inject, serve.
        assert_eq!(out.matches("request_header -X-RepoBox-*").count(), 3);
        assert_eq!(out.matches("forward_auth 127.0.0.1:3230 {").count(), 3);
        assert_eq!(
            out.matches("copy_headers X-RepoBox-User X-RepoBox-User-Id X-RepoBox-Role X-RepoBox-Auth X-RepoBox-App").count(),
            3
        );
        let all = [public, legacy, ok];
        let pending: Vec<&str> = pending_private(&all)
            .iter()
            .map(|a| a.name.as_str())
            .collect();
        assert_eq!(
            pending,
            ["legacy"],
            "only private apps without the contract"
        );
    }

    #[test]
    fn rejects_unsafe_input() {
        assert!(render(&[app("bad name", AppKind::Proxy, "127.0.0.1:1")], &cfg()).is_err());
        assert!(render(&[app("auth", AppKind::Proxy, "127.0.0.1:1")], &cfg()).is_err());
        assert!(render(&[app("x", AppKind::Proxy, "0.0.0.0:1")], &cfg()).is_err());
        assert!(
            render(&[app("x", AppKind::Static, "/etc")], &cfg()).is_err(),
            "outside apps root"
        );
        // a second allowed root admits exactly that subtree, nothing else
        let mut multi = cfg();
        multi.apps_roots.push("/var/www/repo.box/subdomains".into());
        let ok = render(
            &[app(
                "puzzlenest",
                AppKind::Static,
                "/var/www/repo.box/subdomains/circuit",
            )],
            &multi,
        )
        .unwrap();
        assert!(ok.contains("root * /var/www/repo.box/subdomains/circuit\n\t\tfile_server"));
        assert!(
            render(
                &[app("x", AppKind::Static, "/var/www/repo.box/subdomains")],
                &multi
            )
            .is_err(),
            "the root itself is not under the root"
        );
        assert!(
            render(
                &[app("x", AppKind::Static, "/var/www/repo.box/other")],
                &multi
            )
            .is_err()
        );
        assert!(
            render(
                &[app(
                    "x",
                    AppKind::Static,
                    "/var/www/repo.box/subdomains/circuit"
                )],
                &cfg()
            )
            .is_err(),
            "not allowed when the root is not configured"
        );
        let mut none = cfg();
        none.apps_roots.clear();
        assert!(
            render(
                &[app("s", AppKind::Static, "/srv/repobox-platform/apps/s")],
                &none
            )
            .is_err(),
            "no roots means no static apps"
        );
        assert!(
            render(
                &[app("x", AppKind::Static, "/srv/repobox-platform/apps/../x")],
                &cfg()
            )
            .is_err()
        );
        let dup = [
            app("x", AppKind::Proxy, "127.0.0.1:1"),
            app("x", AppKind::Proxy, "127.0.0.1:2"),
        ];
        assert!(render(&dup, &cfg()).is_err());
        let mut c = cfg();
        c.gate = "0.0.0.0:3230".into();
        assert!(render(&[app("x", AppKind::Proxy, "127.0.0.1:1")], &c).is_err());
    }
}
