#!/usr/bin/env python3
"""Apply (or roll back) the repobox-platform managed configuration in Caddy.

Runs ON THE WEB HOST as root (via sudo). It never prints file contents.

apply BLOCK [--apps RENDERED] [--retire HOST ...] [--dry-run]:
  1. build a candidate Caddyfile: replace either the existing managed block
     (between the BEGIN/END markers) or the exact legacy
     `auth.repo.box { ... reverse_proxy 127.0.0.1:3005 }` block with BLOCK;
     refuse if neither matches exactly
  2. --retire: remove the exact standalone legacy site block of each HOST from
     the candidate. Every HOST must be defined by exactly one top-level site
     block outside the managed block, that block may serve only hosts being
     retired, and the rendered routes must already define the host (so no
     hostname is ever left without a route, and none is defined twice)
  3. --apps: the freshly rendered managed routes to install at
     /etc/caddy/repobox-platform/apps.caddy (validated as part of the same
     candidate, backed up and restored with it)
  4. back up the Caddyfile (and apps.caddy) to /etc/caddy/backups/, install the
     apps file, `caddy validate` the candidate; only then move it into place
     and reload. Any failure restores every backed-up file. --dry-run stops
     after validation and installs nothing.
  5. print the backup paths (the rollback route)

rollback CADDYFILE_BACKUP [--apps APPS_BACKUP]:
  restore the given backup(s), validate and reload.
"""
import argparse, os, re, shutil, subprocess, sys, tempfile, time

CADDY_DIR = "/etc/caddy"
CADDYFILE = "/etc/caddy/Caddyfile"
APPS_FILE = "/etc/caddy/repobox-platform/apps.caddy"
BACKUP_DIR = "/etc/caddy/backups"
BEGIN = "# BEGIN repobox-platform managed\n"
END = "# END repobox-platform managed\n"
APPS_HEADER = "# GENERATED by `repobox-platform routes render`."

LEGACY_BLOCK = (
    "auth.repo.box {\n"
    "\theader {\n"
    "\t\tX-Content-Type-Options \"nosniff\"\n"
    "\t\tX-Frame-Options \"DENY\"\n"
    "\t\tReferrer-Policy \"strict-origin-when-cross-origin\"\n"
    "\t\tStrict-Transport-Security \"max-age=31536000; includeSubDomains; preload\"\n"
    "\t}\n"
    "\treverse_proxy 127.0.0.1:3005\n"
    "}\n"
)


# The live Caddyfile must stay world-readable: `caddy reload` runs as the
# caddy user, while backups are root-only (0640). Copying a backup's mode onto
# the live file breaks every subsequent reload with "permission denied".
LIVE_MODE = 0o644

HOST_RE = re.compile(r"^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$")


def install_live(src, dest=CADDYFILE):
    tmp = dest + ".restore"
    shutil.copyfile(src, tmp)
    os.chmod(tmp, LIVE_MODE)
    os.replace(tmp, dest)


def run(cmd):
    return subprocess.run(cmd, capture_output=True, text=True)


def validate(path):
    r = run(["caddy", "validate", "--config", path, "--adapter", "caddyfile"])
    if r.returncode != 0:
        sys.stderr.write("caddy validate FAILED:\n" + r.stderr[-2000:] + "\n")
    else:
        print("caddy validate: OK")
    return r.returncode == 0


def reload():
    r = run(["systemctl", "reload", "caddy"])
    if r.returncode != 0:
        sys.stderr.write("caddy reload FAILED:\n" + r.stderr[-2000:] + "\n")
        return False
    print("caddy reload: OK")
    return True


# ----------------------------------------------------------------- parsing

_QUOTED = re.compile(r'"(?:[^"\\]|\\.)*"')
_PLACEHOLDER = re.compile(r"\{[^{}\s]+\}")


def _depth_delta(line):
    """Net brace depth change of one Caddyfile line, ignoring braces inside
    quoted strings and `{placeholders}`."""
    code = line.split("#", 1)[0] if line.lstrip().startswith("#") else line
    code = _QUOTED.sub("", code)
    code = _PLACEHOLDER.sub("", code)
    return code.count("{") - code.count("}")


def _header_hosts(line):
    """Site addresses of a top-level block header (`a.example, b.example {`),
    or None when the line is not a site block header."""
    s = line.rstrip()
    if not s.endswith("{") or s.startswith((" ", "\t", "#", "(")):
        return None
    addr = s[:-1].strip()
    if not addr:
        return None  # global options block
    return [a.strip() for a in addr.split(",")]


def _bare_host(addr):
    a = addr.strip()
    a = re.sub(r"^[a-z]+://", "", a)
    return a.split(":", 1)[0].split("/", 1)[0]


def top_level_blocks(text):
    """Yield (start, end, hosts) line-index ranges of every top-level site
    block, `end` exclusive, plus (start, end, None) for the managed block."""
    lines = text.split("\n")
    depth = 0
    i = 0
    while i < len(lines):
        line = lines[i]
        if depth == 0 and line + "\n" == BEGIN:
            j = i
            while j < len(lines) and lines[j] + "\n" != END:
                j += 1
            yield (i, j + 1, None)
            i = j + 1
            continue
        hosts = _header_hosts(line) if depth == 0 else None
        d = _depth_delta(line)
        if hosts is not None and d > 0:
            start = i
            depth += d
            i += 1
            while i < len(lines) and depth > 0:
                depth += _depth_delta(lines[i])
                i += 1
            if depth != 0:
                sys.exit(f"unbalanced braces after line {start + 1}; refusing to edit")
            yield (start, i, hosts)
            continue
        depth += d
        i += 1


def site_hosts_in(text):
    hosts = []
    for _, _, h in top_level_blocks(text):
        if h:
            hosts.extend(_bare_host(a) for a in h)
    return hosts


def retire_blocks(candidate, hosts, apps_text):
    """Remove the exact standalone site block of every host in `hosts`."""
    hosts = sorted(set(hosts))
    for h in hosts:
        if not HOST_RE.match(h):
            sys.exit(f"refusing to retire '{h}': not a plain hostname")
    generated = site_hosts_in(apps_text)
    for h in hosts:
        n = generated.count(h)
        if n != 1:
            sys.exit(
                f"refusing to retire {h}: the rendered routes define it {n} time(s), need exactly 1"
            )
    blocks = list(top_level_blocks(candidate))
    wanted = set(hosts)
    remove = []
    for start, end, bhosts in blocks:
        if not bhosts:
            continue
        bare = [_bare_host(a) for a in bhosts]
        if not wanted.intersection(bare):
            continue
        if any(a != _bare_host(a) for a in bhosts):
            sys.exit(f"refusing to retire block at line {start + 1}: address with scheme/port/path")
        extra = sorted(set(bare) - wanted)
        if extra:
            sys.exit(
                f"refusing to retire block at line {start + 1}: it also serves {', '.join(extra)}"
            )
        remove.append((start, end, bare))
    for h in hosts:
        n = sum(1 for _, _, b in remove if h in b)
        if n != 1:
            sys.exit(f"refusing to retire {h}: found {n} site block(s) in the Caddyfile, need exactly 1")
    lines = candidate.split("\n")
    keep = [True] * len(lines)
    for start, end, bare in remove:
        # take the block plus the comment lines glued directly above it
        s = start
        while s > 0 and lines[s - 1].startswith("#"):
            s -= 1
        for k in range(s, end):
            keep[k] = False
        print(f"retire: {', '.join(bare)} (lines {s + 1}-{end})")
    # blank lines that only became neighbours because a block between them
    # went away collapse into one; untouched text keeps its spacing
    out = []
    prev_idx = None
    for idx, (line, k) in enumerate(zip(lines, keep)):
        if not k:
            continue
        if (
            line.strip() == ""
            and out
            and out[-1].strip() == ""
            and prev_idx is not None
            and idx != prev_idx + 1
        ):
            continue
        out.append(line)
        prev_idx = idx
    return "\n".join(out)


# ------------------------------------------------------------------- apply

def backup_path(name, stamp):
    return os.path.join(BACKUP_DIR, f"{name}.pre-repobox-platform-{stamp}")


def apply(block_path, apps_path=None, retire=(), dry_run=False):
    with open(CADDYFILE) as f:
        current = f.read()
    with open(block_path) as f:
        block = f.read()
    if not (block.startswith(BEGIN) and block.endswith(END)):
        sys.exit("managed block file must start/end with the markers")
    # `routes render` deliberately uses the same outer markers for its generated
    # app fragment. Never accept that fragment as the control-plane block: doing
    # so would remove auth.repo.box while leaving superficially valid Caddy.
    required = ("auth.repo.box {", f"import {APPS_FILE}")
    if not all(item in block for item in required):
        sys.exit("refusing non-control-plane managed block; auth route/import required")

    if BEGIN in current:
        start = current.index(BEGIN)
        end = current.index(END, start) + len(END)
        candidate = current[:start] + block + current[end:]
        mode = "updated existing managed block"
    elif current.count(LEGACY_BLOCK) == 1:
        candidate = current.replace(LEGACY_BLOCK, block, 1)
        mode = "replaced legacy auth.repo.box block (3005) with managed block"
    else:
        n = len(re.findall(r"^auth\.repo\.box\b", current, re.M))
        sys.exit(
            f"CONFLICT: no managed block and the legacy auth.repo.box block does not match exactly "
            f"({n} auth.repo.box site definitions found). Nothing changed; inspect the Caddyfile by hand."
        )

    apps_new = None
    apps_current = None
    if os.path.isfile(APPS_FILE):
        with open(APPS_FILE) as f:
            apps_current = f.read()
    if apps_path is not None:
        with open(apps_path) as f:
            apps_new = f.read()
        if not apps_new.startswith(APPS_HEADER):
            sys.exit("--apps must be the output of `repobox-platform routes render`")
    apps_effective = apps_new if apps_new is not None else (apps_current or "")
    if retire:
        candidate = retire_blocks(candidate, retire, apps_effective)

    # a hostname defined both by a legacy block and by a generated route is a
    # duplicate site definition; Caddy would reject it, but say why first
    dup = sorted(set(site_hosts_in(candidate)).intersection(site_hosts_in(apps_effective)))
    if dup:
        sys.exit(f"CONFLICT: defined in both the Caddyfile and the rendered routes: {', '.join(dup)}"
                 " (retire the legacy block with --retire)")

    apps_changed = apps_new is not None and apps_new != apps_current
    if candidate == current and not apps_changed:
        print("no change needed")
        return
    if candidate == current:
        mode = "managed block unchanged"

    os.makedirs(BACKUP_DIR, exist_ok=True)
    stamp = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    backup = backup_path("Caddyfile", stamp)
    apps_backup = None
    if apps_changed and apps_current is not None:
        apps_backup = backup_path("apps.caddy", stamp)
    if dry_run:
        # validate the candidate against a private copy of the new apps file
        with tempfile.TemporaryDirectory(dir=CADDY_DIR) as d:
            apps_tmp = os.path.join(d, "apps.caddy")
            with open(apps_tmp, "w") as f:
                f.write(apps_effective)
            cand_tmp = os.path.join(d, "Caddyfile")
            with open(cand_tmp, "w") as f:
                f.write(candidate.replace(f"import {APPS_FILE}", f"import {apps_tmp}"))
            ok = validate(cand_tmp)
        print(f"dry run: {mode}; apps.caddy {'would change' if apps_changed else 'unchanged'}; nothing installed")
        sys.exit(0 if ok else 1)

    shutil.copy2(CADDYFILE, backup)
    os.chmod(backup, 0o640)
    if apps_backup:
        shutil.copy2(APPS_FILE, apps_backup)
        os.chmod(apps_backup, 0o640)

    def restore_apps():
        if not apps_changed:
            return
        if apps_backup:
            install_live(apps_backup, APPS_FILE)
        else:
            os.unlink(APPS_FILE)

    if apps_changed:
        os.makedirs(os.path.dirname(APPS_FILE), exist_ok=True)
        install_live(apps_path, APPS_FILE)
    fd, tmp = tempfile.mkstemp(prefix="Caddyfile.candidate.", dir=CADDY_DIR)
    with os.fdopen(fd, "w") as f:
        f.write(candidate)
    if not validate(tmp):
        os.unlink(tmp)
        restore_apps()
        sys.exit(f"candidate rejected; live Caddyfile untouched (backup at {backup})")
    os.chmod(tmp, LIVE_MODE)
    os.replace(tmp, CADDYFILE)
    print(mode + ("; apps.caddy updated" if apps_changed else ""))
    if not reload():
        install_live(backup)
        restore_apps()
        reload()
        sys.exit("reload failed; restored previous Caddyfile" + (" and apps.caddy" if apps_changed else ""))
    print(f"backup: {backup}")
    if apps_backup:
        print(f"apps backup: {apps_backup}")
    print(
        f"rollback: sudo python3 {os.path.abspath(__file__)} rollback {backup}"
        + (f" --apps {apps_backup}" if apps_backup else "")
    )


def rollback(backup, apps_backup=None):
    if not os.path.isfile(backup):
        sys.exit(f"no such backup {backup}")
    if apps_backup and not os.path.isfile(apps_backup):
        sys.exit(f"no such apps backup {apps_backup}")
    if apps_backup:
        install_live(apps_backup, APPS_FILE)
        print(f"restored {apps_backup}")
    if not validate(backup):
        sys.exit("backup does not validate; Caddyfile not applied")
    install_live(backup)
    if not reload():
        sys.exit("reload failed after restore")
    print(f"restored {backup}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("apply")
    a.add_argument("block")
    a.add_argument("--apps", help="freshly rendered apps.caddy to install alongside")
    a.add_argument("--retire", action="append", default=[], metavar="HOST",
                   help="remove this host's standalone legacy site block (repeatable)")
    a.add_argument("--dry-run", action="store_true")
    r = sub.add_parser("rollback")
    r.add_argument("backup")
    r.add_argument("--apps", help="apps.caddy backup to restore first")
    args = ap.parse_args()
    if os.geteuid() != 0:
        sys.exit("run with sudo")
    if args.cmd == "apply":
        apply(args.block, args.apps, args.retire, args.dry_run)
    else:
        rollback(args.backup, args.apps)
