version: 1.0.0
identities: {}
groups:
  security:
    name: Security
    members: []
    includes: null
  engineering:
    name: Engineering
    members: []
    includes: null
  admins:
    name: Administrators
    members: []
    includes:
    - security
permissions:
  admin_all:
    actors:
    - admins
    verbs:
    - push
    - pull
    - merge
    - admin
    targets:
    - '*'
  engineering_development:
    actors:
    - engineering
    verbs:
    - push
    - pull
    targets:
    - development/*
repos: null
defaults:
  identity: null
  signing_required: true
  auto_verify: false
aliases: null
