"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { RegMarks } from "@/components/RegMarks";
import { BackgroundCanvas } from "@/components/BackgroundCanvas";
import {
  projects,
  getStatusBadgeColor,
  getStatusBadgeBackground,
  type Project,
} from "@/data/projects";

// REPOBOX-PROOF-001 (2026-09-06).
//
// This page used to render public/data/portfolio.json, which was generated on
// 2026-03-30 by a script that treated every kanban markdown file in
// /home/xiko/kanban-projects as a project. The public result listed "Banger
// Kanban" and "OCR Receipts Kanban" as portfolio entries, described them with
// their HTML config comments, and linked several of them to hosts that no
// longer answer.
//
// It now takes project identity from src/data/projects.ts — the same
// hand-swept list /projects uses, where every link has been fetched — and
// merges in git activity from public/data/repo-activity.json, which is
// regenerated by tools/generate-portfolio-data.js and contains only commit
// counts and dates for repositories that exist on the build host. A project
// with no local checkout simply shows no activity line, rather than zeros.

interface RepoActivity {
  commits: number;
  lastCommit: string | null;
  weeklyCommits: number;
}

interface RepoActivityFile {
  generatedAt: string;
  note?: string;
  repos: Record<string, RepoActivity>;
}

function relativeDay(iso: string | null): string | null {
  if (!iso) return null;
  const days = Math.floor((Date.now() - new Date(iso).getTime()) / 86_400_000);
  if (days <= 0) return "today";
  if (days === 1) return "yesterday";
  if (days < 7) return `${days}d ago`;
  if (days < 30) return `${Math.floor(days / 7)}w ago`;
  return `${Math.floor(days / 30)}mo ago`;
}

function PortfolioCard({
  project,
  activity,
}: {
  project: Project;
  activity?: RepoActivity;
}) {
  const isExternal = Boolean(project.link);

  return (
    <div
      className="project-card"
      style={{
        position: "relative",
        overflow: "hidden",
        background: "var(--bp-surface)",
        border: "1px solid var(--bp-border)",
        borderRadius: 8,
        padding: 20,
        transition: "all 0.2s ease",
      }}
    >
      <svg className="card-border">
        <rect x="0.5" y="0.5" width="calc(100% - 1px)" height="calc(100% - 1px)" />
      </svg>

      <div style={{ position: "relative", zIndex: 2 }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-start",
            marginBottom: 8,
          }}
        >
          <div
            style={{
              fontWeight: 700,
              fontSize: 16,
              lineHeight: "20px",
              color: "#ffffff",
              flex: 1,
              marginRight: 12,
            }}
          >
            {project.name}
          </div>
          <span
            style={{
              fontSize: 11,
              lineHeight: "18px",
              color: getStatusBadgeColor(project.status),
              background: getStatusBadgeBackground(project.status),
              padding: "2px 8px",
              borderRadius: 2,
              fontWeight: 600,
              textTransform: "uppercase",
              whiteSpace: "nowrap",
            }}
          >
            {project.status}
          </span>
        </div>

        <div
          style={{
            fontSize: 12,
            lineHeight: "18px",
            color: "var(--bp-text)",
            marginBottom: 12,
          }}
        >
          {project.description}
        </div>

        {project.retiredNote && (
          <div
            style={{
              fontSize: 11,
              lineHeight: "16px",
              color: "var(--bp-dim)",
              borderLeft: "2px solid var(--bp-border)",
              paddingLeft: 10,
              marginBottom: 12,
            }}
          >
            {project.retiredNote}
          </div>
        )}

        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            fontSize: 11,
            color: "var(--bp-dim)",
            gap: 12,
          }}
        >
          <div style={{ display: "flex", gap: 12 }}>
            {activity ? (
              <>
                <span>{activity.commits} commits</span>
                {activity.weeklyCommits > 0 && (
                  <span style={{ color: "#4ade80" }}>
                    +{activity.weeklyCommits} this week
                  </span>
                )}
              </>
            ) : (
              <span style={{ opacity: 0.7 }}>no local checkout</span>
            )}
          </div>
          {activity?.lastCommit && (
            <span style={{ opacity: 0.8, whiteSpace: "nowrap" }}>
              {relativeDay(activity.lastCommit)}
            </span>
          )}
        </div>

        {isExternal && (
          <a
            href={project.link}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              display: "inline-block",
              marginTop: 12,
              fontSize: 11,
              color: "var(--bp-accent)",
              textDecoration: "none",
              border: "1px solid var(--bp-accent)",
              padding: "4px 12px",
              borderRadius: 2,
            }}
          >
            {project.link?.replace(/^https?:\/\//, "")} →
          </a>
        )}
      </div>
    </div>
  );
}

function PortfolioSection({
  title,
  entries,
  description,
  activity,
}: {
  title: string;
  entries: Project[];
  description?: string;
  activity: Record<string, RepoActivity>;
}) {
  if (entries.length === 0) return null;

  return (
    <section style={{ marginBottom: 48 }}>
      <div style={{ marginBottom: 20 }}>
        <h3
          style={{
            fontSize: 14,
            lineHeight: "20px",
            textTransform: "uppercase",
            letterSpacing: "0.12em",
            color: "var(--bp-accent)",
            fontWeight: 600,
            marginBottom: 4,
          }}
        >
          {title} ({entries.length})
        </h3>
        {description && (
          <p style={{ fontSize: 12, color: "var(--bp-dim)", margin: 0 }}>
            {description}
          </p>
        )}
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
          gap: 16,
        }}
      >
        {entries.map((project) => (
          <PortfolioCard
            key={project.id}
            project={project}
            activity={activity[project.id]}
          />
        ))}
      </div>
    </section>
  );
}

export default function PortfolioPage() {
  const pageRef = useRef<HTMLElement>(null);
  const [activityFile, setActivityFile] = useState<RepoActivityFile | null>(null);

  useEffect(() => {
    // Activity is supplementary. If it fails to load the page still renders
    // every project, just without commit counts — the project list is compiled
    // in, not fetched.
    fetch("/data/repo-activity.json")
      .then((res) => (res.ok ? res.json() : null))
      .then((data) => setActivityFile(data))
      .catch(() => setActivityFile(null));
  }, []);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) e.target.classList.add("visible");
        });
      },
      { threshold: 0.1 }
    );
    if (pageRef.current) observer.observe(pageRef.current);
    return () => observer.disconnect();
  }, []);

  const activity = activityFile?.repos ?? {};

  const active = projects.filter((p) => p.status === "active");
  const shipped = projects.filter((p) => p.status === "shipped");
  const paused = projects.filter((p) => p.status === "paused");
  const concept = projects.filter((p) => p.status === "concept");
  const retired = projects.filter((p) => p.status === "retired");

  const tracked = Object.values(activity);
  const totalCommits = tracked.reduce((sum, r) => sum + r.commits, 0);
  const weeklyCommits = tracked.reduce((sum, r) => sum + r.weeklyCommits, 0);

  return (
    <>
      <RegMarks />
      <div
        style={{
          maxWidth: 900,
          margin: "0 auto",
          position: "relative",
          zIndex: 2,
          padding: "80px 40px 100px",
        }}
      >
        <header style={{ marginBottom: 60 }}>
          <nav style={{ display: "flex", gap: 16, marginBottom: 24, fontSize: 12 }}>
            <Link href="/" style={{ color: "var(--bp-dim)" }}>
              ← home
            </Link>
            <Link href="/projects" style={{ color: "var(--bp-dim)" }}>
              projects
            </Link>
            <Link href="/building" style={{ color: "var(--bp-dim)" }}>
              building
            </Link>
          </nav>

          <div
            className="font-mono font-bold"
            style={{ fontSize: 36, lineHeight: 1.1, marginBottom: 16 }}
          >
            Portfolio Wall
          </div>

          <p
            style={{
              fontSize: 16,
              lineHeight: "24px",
              color: "var(--bp-dim)",
              maxWidth: 620,
              marginBottom: 32,
            }}
          >
            Everything built here, including the parts that are switched off.
            Status is set by hand and every outbound link is checked before it
            goes on the page; retired entries say what happened rather than
            disappearing. Commit counts come from the repositories on the build
            host, so a project with no checkout here shows none.
          </p>
        </header>

        {tracked.length > 0 && (
          <section
            style={{
              background: "var(--bp-surface)",
              border: "1px solid var(--bp-border)",
              borderRadius: 8,
              padding: 24,
              marginBottom: 48,
            }}
          >
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
                gap: 20,
                textAlign: "center",
              }}
            >
              <div>
                <div style={{ fontSize: 28, fontWeight: 700, color: "var(--bp-accent)" }}>
                  {projects.length}
                </div>
                <div style={{ fontSize: 12, color: "var(--bp-dim)", textTransform: "uppercase" }}>
                  Projects listed
                </div>
              </div>
              <div>
                <div style={{ fontSize: 28, fontWeight: 700, color: "#4ade80" }}>
                  {active.length}
                </div>
                <div style={{ fontSize: 12, color: "var(--bp-dim)", textTransform: "uppercase" }}>
                  Active
                </div>
              </div>
              <div>
                <div style={{ fontSize: 28, fontWeight: 700, color: "var(--bp-accent)" }}>
                  {totalCommits}
                </div>
                <div style={{ fontSize: 12, color: "var(--bp-dim)", textTransform: "uppercase" }}>
                  Commits, {tracked.length} repos
                </div>
              </div>
              <div>
                <div style={{ fontSize: 28, fontWeight: 700, color: "#4ade80" }}>
                  {weeklyCommits}
                </div>
                <div style={{ fontSize: 12, color: "var(--bp-dim)", textTransform: "uppercase" }}>
                  This week
                </div>
              </div>
            </div>

            {activityFile?.generatedAt && (
              <div
                style={{
                  textAlign: "center",
                  marginTop: 16,
                  fontSize: 11,
                  color: "var(--bp-dim)",
                }}
              >
                Activity measured {new Date(activityFile.generatedAt).toLocaleString()}
              </div>
            )}
          </section>
        )}

        <main ref={pageRef} className="reveal">
          <PortfolioSection
            title="Active"
            entries={active}
            description="Being worked on now"
            activity={activity}
          />
          <PortfolioSection
            title="Shipped"
            entries={shipped}
            description="Finished and still running"
            activity={activity}
          />
          <PortfolioSection
            title="Paused"
            entries={paused}
            description="Not abandoned, just not current"
            activity={activity}
          />
          <PortfolioSection
            title="Concept"
            entries={concept}
            description="Documented ideas without a build"
            activity={activity}
          />
          <PortfolioSection
            title="Retired"
            entries={retired}
            description="No longer running. Kept because the work happened."
            activity={activity}
          />
        </main>

        <footer
          style={{
            marginTop: 60,
            textAlign: "center",
            fontSize: 11,
            color: "var(--bp-dim)",
          }}
        >
          <p>
            Project list and links are maintained by hand in src/data/projects.ts
            and swept before publication.
            <br />
            Commit activity is regenerated by tools/generate-portfolio-data.js.
          </p>
        </footer>
      </div>
      <BackgroundCanvas />
    </>
  );
}
